name: opiskelu

services:
  dev:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  vite:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
